### ISSUE TITLE
Watu wapende bafu!

### ISSUE THREAD

**Issue by sokorototo** [GithinjiHans/Locations_Search_Engine#1]
> Despite being written in Rust, this code **needs** a shower!!

**Comment by GithinjiHans** [comment]
we mzee

**Comment by sokorototo** [comment]
![IMG20230605012301.jpg](https://github.com/GithinjiHans/API2/assets/53893043/258b7047-de04-4450-a8cf-f2ad63a5d919)

Hii sufuria inakungojea!
